#!/bin/bash

# update and deploy the swdeploy application and service and restart it.

TAG=`git tag --points-at HEAD`
REMOTE="nginxservice.lwa.pvt/deployments"
TARBALL="swdeploy_$TAG.tar.gz"

function create_symlink() {
    hn=`hostname`
    if [[ -e deployCfg.yml ]]; then
        rm -f deployCfg.yml
    fi
    if [[ $hn =~ "mcs" ]]; then
        ln -s deployCfg_mcs.yml deployCfg.yml
    elif [[ $hn =~ "lwacr" ]]; then
        ln -s deployCfg_cr.yml deployCfg.yml
    elif [[ $hn =~ "gpu" ]]; then
        ln -s deployCfg_gpu.yml deployCfg.yml
    elif [[ $hn =~ "calim" ]]; then
        ln -s deployCfg_calim.yml deployCfg.yml
    fi
}

mkdir -p /home/ubuntu/bin
cd /home/ubuntu/bin
if [[ -e $TARBALL ]]; then
    rm $TARBALL
fi
wget --no-check-certificate $REMOTE/$TARBALL
tar xf $TARBALL
cd -
cd /home/ubuntu/bin/deploy
create_symlink
cd -

sudo cp systemd/swdeploy.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable swdeploy
sudo systemctl restart swdeploy

